import path from "node:path"
import isRegularDirectorySync from "./fs/isRegularDirectorySync.mjs"
import scandirSync from "./fs/scandirSync.mjs"

function determineDirsThatWillBeGenerated(files_list) {
	let dirs = {}

	for (const [file_path] of files_list) {
		dirs[path.dirname(file_path)] = 1
	}

	return Object.keys(dirs)
}

function difference(a1, a2) {
	return a1.filter(item => !a2.includes(item))
}

export default function(destination_dir, files_list) {
	// return empty list if dir doesn't exist yet
	if (!isRegularDirectorySync(destination_dir)) {
		return []
	}

	let ret = []

	const destination_dir_entries = scandirSync(destination_dir)

	const dirs_that_will_be_autogenerated = determineDirsThatWillBeGenerated(files_list)
	const existing_dirs = destination_dir_entries.filter(entry => {
		return entry.type === "dir"
	}).map(entry => entry.relative_path)
	const dirs_to_delete = difference(existing_dirs, dirs_that_will_be_autogenerated)

	const files_that_will_be_autogenerated = files_list.map(entry => {
		return entry[0]
	})
	const existing_files = destination_dir_entries.filter(entry => {
		return entry.type === "file"
	}).map(entry => entry.relative_path)
	const files_to_delete = difference(existing_files, files_that_will_be_autogenerated)

	return [
		// delete files first, then directories
		...files_to_delete,
		...dirs_to_delete
	]
}
